name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: hello world
        run:  |
          echo "Hello deployment"
      - name: Install dependencies
        run: |
          make install